# Generated by Django 5.2.9 on 2026-03-17 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0012_deprecate_case_versioning"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="case_id",
            field=models.CharField(
                db_index=True,
                help_text="Stable unique identifier for this case",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Internal notes about the case (markdown supported)",
            ),
        ),
        migrations.AlterField(
            model_name="documentsource",
            name="source_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LEGAL_COURT_ORDER", "Legal: Court Order/Verdict"),
                    ("LEGAL_PROCEDURAL", "Legal: Procedural/Law Enforcement"),
                    ("OFFICIAL_GOVERNMENT", "Official (Government)"),
                    ("FINANCIAL_FORENSIC", "Financial/Forensic Record"),
                    ("INTERNAL_CORPORATE", "Internal Corporate Doc"),
                    ("MEDIA_NEWS", "Media/News"),
                    ("INVESTIGATIVE_REPORT", "Investigative Report"),
                    ("PUBLIC_COMPLAINT", "Public Complaint/Whistleblower"),
                    ("LEGISLATIVE_DOC", "Legislative/Policy Doc"),
                    ("SOCIAL_MEDIA", "Social Media"),
                    ("OTHER_VISUAL", "Other / Visual Assets"),
                ],
                help_text="Type of source",
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="CaseEntityRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("alleged", "Alleged"),
                            ("related", "Related"),
                            ("witness", "Witness"),
                            ("opposition", "Opposition"),
                            ("victim", "Victim"),
                        ],
                        help_text="Type of relationship between case and entity",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=500,
                        help_text="Optional notes about this relationship",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this relationship was created",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        help_text="The case this relationship belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_relationships",
                        to="cases.case",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        help_text="The entity involved in this relationship",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_relationships",
                        to="cases.jawafentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Case Entity Relationship",
                "verbose_name_plural": "Case Entity Relationships",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="case",
            name="unified_entities",
            field=models.ManyToManyField(
                help_text="All entities related to this case through the unified relationship system",
                related_name="unified_cases",
                through="cases.CaseEntityRelationship",
                to="cases.jawafentity",
            ),
        ),
        migrations.AddIndex(
            model_name="caseentityrelationship",
            index=models.Index(
                fields=["case", "relationship_type"], name="case_relationship_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caseentityrelationship",
            index=models.Index(
                fields=["entity", "relationship_type"],
                name="entity_relationship_type_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="caseentityrelationship",
            constraint=models.UniqueConstraint(
                fields=("case", "entity", "relationship_type"),
                name="unique_case_entity_relationship_type",
            ),
        ),
    ]
