# Generated by Django 6.0.3 on 2026-03-17 13:23

from django.db import migrations


def migrate_existing_relationships(apps, schema_editor):
    """
    Copy existing alleged_entities and related_entities relationships
    to the new CaseEntityRelationship through-model.

    This migration preserves all existing data by:
    1. Copying alleged_entities with relationship_type="alleged"
    2. Copying related_entities with relationship_type="related"
    3. Using get_or_create to handle potential duplicates gracefully
    4. Gracefully handling cases where old ManyToMany tables don't exist
    """
    from django.db import connection

    Case = apps.get_model("cases", "Case")
    CaseEntityRelationship = apps.get_model("cases", "CaseEntityRelationship")

    # Track migration statistics
    alleged_migrated = 0
    related_migrated = 0
    duplicates_skipped = 0

    # Check if the old ManyToMany tables exist
    table_names = connection.introspection.table_names()
    alleged_table_exists = "cases_case_alleged_entities" in table_names
    related_table_exists = "cases_case_related_entities" in table_names

    print("Checking for existing data to migrate:")
    print(f"  - alleged_entities table exists: {alleged_table_exists}")
    print(f"  - related_entities table exists: {related_table_exists}")

    # Migrate alleged entities if table exists
    if alleged_table_exists:
        try:
            for case in Case.objects.prefetch_related("alleged_entities").all():
                for entity in case.alleged_entities.all():
                    relationship, created = (
                        CaseEntityRelationship.objects.get_or_create(
                            case=case,
                            entity=entity,
                            relationship_type="alleged",
                            defaults={"notes": ""},
                        )
                    )
                    if created:
                        alleged_migrated += 1
                    else:
                        duplicates_skipped += 1
        except Exception as e:
            print(f"Warning: Could not migrate alleged_entities: {e}")

    # Migrate related entities if table exists
    if related_table_exists:
        try:
            for case in Case.objects.prefetch_related("related_entities").all():
                for entity in case.related_entities.all():
                    relationship, created = (
                        CaseEntityRelationship.objects.get_or_create(
                            case=case,
                            entity=entity,
                            relationship_type="related",
                            defaults={"notes": ""},
                        )
                    )
                    if created:
                        related_migrated += 1
                    else:
                        duplicates_skipped += 1
        except Exception as e:
            print(f"Warning: Could not migrate related_entities: {e}")

    # Log migration results (will appear in migration output)
    print("Migration completed successfully:")
    print(f"  - Alleged entities migrated: {alleged_migrated}")
    print(f"  - Related entities migrated: {related_migrated}")
    print(f"  - Duplicates skipped: {duplicates_skipped}")
    print(f"  - Total relationships created: {alleged_migrated + related_migrated}")

    if not alleged_table_exists and not related_table_exists:
        print(
            "  - No existing data found to migrate (this is normal for new installations)"
        )


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: Remove CaseEntityRelationship records that were
    created from the original alleged_entities and related_entities fields.

    ROLLBACK-SAFE: Only deletes relationships with:
    - relationship_type in ('alleged', 'related') AND
    - notes = '' (empty notes indicates migrated data)

    This preserves manually created relationships that have notes or other types.
    """
    CaseEntityRelationship = apps.get_model("cases", "CaseEntityRelationship")

    # Count relationships before deletion
    alleged_migrated = CaseEntityRelationship.objects.filter(
        relationship_type="alleged", notes=""
    ).count()

    related_migrated = CaseEntityRelationship.objects.filter(
        relationship_type="related", notes=""
    ).count()

    # Count manually created relationships that will be preserved
    alleged_manual = CaseEntityRelationship.objects.filter(
        relationship_type="alleged"
    ).exclude(notes="").count()

    related_manual = CaseEntityRelationship.objects.filter(
        relationship_type="related"
    ).exclude(notes="").count()

    other_types = CaseEntityRelationship.objects.exclude(
        relationship_type__in=["alleged", "related"]
    ).count()

    # Delete only migrated relationships (with empty notes)
    deleted_count = CaseEntityRelationship.objects.filter(
        relationship_type__in=["alleged", "related"], notes=""
    ).delete()[0]

    print("Reverse migration completed (rollback-safe):")
    print(f"  - Alleged relationships removed (migrated): {alleged_migrated}")
    print(f"  - Related relationships removed (migrated): {related_migrated}")
    print(f"  - Total relationships removed: {deleted_count}")
    print(f"  - Alleged relationships preserved (manual): {alleged_manual}")
    print(f"  - Related relationships preserved (manual): {related_manual}")
    print(f"  - Other relationship types preserved: {other_types}")
    print(f"  - Total relationships preserved: {alleged_manual + related_manual + other_types}")


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0013_add_case_entity_relationship"),
    ]

    operations = [
        migrations.RunPython(
            migrate_existing_relationships,
            reverse_migration,
            elidable=True,
        ),
    ]
